### ISSUE TITLE
Installer fails MD5 check, fails to download all mods.

### ISSUE THREAD

**Issue by SirCanucklehead** [Mord3rca/gamma-launcher#103]
Running up to date Arch, Anomaly 1.5.2, latest GAMMA RC3 download. `gamma-launcher` running from the standalone release, not in a venv.

I run 
`gamma-launcher check-anomaly --anomaly <Anomaly path>` 
and get no errors.

I then run 
`gamma-launcher check-md5 --gamma <GAMMA path>` 
as this github page and DravenusRex's guide says, I get a long output listing all addons and saying they are "not found on disk."

I then run 

./gamma-launcher full-install --anomaly /mnt/SamsungSSD/Lutris/STALKER/drive_c/Anomaly/ --gamma /mnt/SamsungSSD/Lutris/STALKER/drive_c/GAMMA/` 
and this is the output
`[+] Updating G.A.M.M.A. definition
    downloading archive...
  - Downloading Stalker_GAMMA.zip: 302MiB [00:21, 14.5MiB/s] 
[+] Reading /mnt/SamsungSSD/Lutris/STALKER/drive_c/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & /mnt/SamsungSSD/Lutris/STALKER/drive_c/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
[+] Installing mod:  Dux Characters Kit Voices Pack
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip: 234MiB [00:28, 8.56MiB/s] 
    Installing Dux's Innumerable Character Kit Voices Pack -> /mnt/SamsungSSD/Lutris/STALKER/drive_c/GAMMA/mods/305- Dux Characters Kit Voices Pack - Demonized
    Installing Dux's Innumerable Character Kit Voices Pack English ISG -> /mnt/SamsungSSD/Lutris/STALKER/drive_c/GAMMA/mods/305- Dux Characters Kit Voices Pack - Demonized
[+] Installing mod:  Longreed's fixed artefacts spawns under maps
  - Downloading Groks_main_menu_theme.zip: 7.05MiB [00:00, 17.6MiB/s]
[+] Installing mod:  Grulag's Dead Bushes
  - Using cached Groks_main_menu_theme.zip
[+] Installing mod:  Headlamp Animation Fix
  - Downloading 1.0.1_Grok_Gotta_Go_Fast.zip: 3.76kiB [00:00, 31.5kiB/s]
[+] Installing mod:  Safe Areas Transitions
  - Downloading Safe_Start_2.2.zip: 2.96kiB [00:00, 24.3kiB/s]
[+] Installing mod:  Zone Customization Project (ZCP)
  - Downloading zone_customization_project_1.5e.zip: 128kiB [00:00, 969kiB/s]
[+] Installing mod:  Weird Tasks Framework
  - Using cached 1.0.1_Grok_Gotta_Go_Fast.zip
[+] Installing mod:  Bizon Replacer
  - Using cached 1.0.1_Grok_Gotta_Go_Fast.zip
[+] Installing mod:  Xenotech Protects Cordon Base
  - Downloading Combat_Behavior_1.02.4.rar: 28.8kiB [00:00, 249kiB/s]
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/install.py", line 415, in run
  File "launcher/commands/install.py", line 366, in _install_mods
  File "launcher/commands/install.py", line 332, in _install_mod
  File "launcher/archive.py", line 57, in extract_archive
  File "launcher/archive.py", line 49, in <lambda>
  File "rarfile.py", line 875, in extractall
  File "rarfile.py", line 940, in _extract_one
  File "rarfile.py", line 955, in _make_file
  File "shutil.py", line 197, in copyfileobj
  File "rarfile.py", line 2284, in read
rarfile.BadRarFile: Failed the read enough data: req=3178 got=51
[10153] Failed to execute script 'gamma-launcher' due to unhandled exception!

I don't really understand the issue. The launcher seems to not be able to download all the required mods. Do I just need to manually download the addons? I feel like I'm missing a step or something straightforward, but I don't see anything on either this github page or DravenusRex's guide that will help.

**Comment by SirCanucklehead** [comment]
My bad, should have read my outputs more closely. Failed to realize the issue was caused by lack of .rar support. Installed `unrar` and things work as expected.
