### ISSUE TITLE
im going to go insane

### ISSUE THREAD

**Issue by space2ninja101** [Mord3rca/gamma-launcher#124]
please help me figure out what the hell is going on here

i have libmagic and python-magic and everything

i even tried in a venv

im on artix linux its a fork of arch linux without systemd

```
TMPDIR="/run/media/space/games/cache/" ./gamma-launcher full-install --anomaly "/run/media/space/f1ec772b-b5de-43f7-8385-6b45937a30f4/lutris/anomaly/drive_c/Anomaly" --gamma "/run/media/space/games/gamma"
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
[+] Installing base setup for GAMMA
  - Downloading Mod.Organizer-2.4.4.7z: 85.9MiB [00:08, 10.8MiB/s]
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
  File "launcher/commands/install.py", line 337, in run
  File "launcher/commands/install.py", line 167, in run
  File "launcher/commands/install.py", line 151, in _install_mod_organizer
  File "launcher/archive.py", line 60, in extract_archive
  File "magic/__init__.py", line 178, in from_file
  File "magic/__init__.py", line 165, in _get_magic_type
  File "magic/__init__.py", line 73, in __init__
  File "magic/__init__.py", line 332, in magic_load
  File "magic/__init__.py", line 225, in errorcheck_negative_one
magic.MagicException: b'could not find any valid magic files!'
[29917] Failed to execute script 'gamma-launcher' due to unhandled exception!
```

**Comment by space2ninja101** [comment]
i got this now when i applied the env variable
update your magic thing
`File 5.41 supports only version 16 magic files. `/usr/share/file/misc/magic.mgc' is version 18`

**Comment by space2ninja101** [comment]
nevermind fixed it i couldnt find how to build a version 16 magic file but i found a version 16 magic file in my lutris cache for proton

**Comment by Mord3rca** [comment]
@space2ninja101 Using latest branch (master) and venv installation should resolve this since `magic` module is no longer used.

**Comment by Mord3rca** [comment]
> nevermind fixed it i couldnt find how to build a version 16 magic file but i found a version 16 magic file in my lutris cache for proton

Resolved
