### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by Mitchell-Lewis** [Mord3rca/gamma-launcher#134]
./gamma-launcher anomaly-install --anomaly .

/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
[+] Installing base Anomaly 1.5.1
- Downloading Anomaly-1.5.1.2.7z: 8.75GiB [16:16, 9.62MiB/s]
- Extracting
sh: symbol lookup error: sh: undefined symbol: rl_trim_arg_from_keyseq
Traceback (most recent call last):
File "gamma-launcher.py", line 8, in <module>
File "launcher/cli.py", line 68, in main
File "launcher/commands/install.py", line 98, in run
File "launcher/commands/install.py", line 83, in _install_component
File "launcher/archive.py", line 61, in extract_archive
File "launcher/archive.py", line 49, in _7zip_bcj2_workaround
RuntimeError: 7z error will decompressing Anomaly-1.5.1.2.7z
[398277] Failed to execute script 'gamma-launcher' due to unhandled exception!

**Comment by Mord3rca** [comment]
Please use venv installation to get rid of python-magic dependency

**Comment by Mitchell-Lewis** [comment]
I used venv and tried to build and run from source following your instructions but i keep getting an error
Hence why i used the prebuilt release.

here is the issue i get.
```
╭─mitchell@MINDA in repo: gamma-launcher on  master [?] via  v3.12.4 (env) took 8s
╰─λ gamma-launcher anomaly-install --anomaly ..
Traceback (most recent call last):
File "/mnt/Misc/Stalker/env/bin/gamma-launcher", line 5, in <module>
from launcher.cli import main
File "/mnt/Misc/Stalker/env/lib/python3.12/site-packages/launcher/cli.py", line 2, in <module>
from launcher.commands import (
File "/mnt/Misc/Stalker/env/lib/python3.12/site-packages/launcher/commands/__init__.py", line 1, in <module>
from .check import CheckAnomaly, CheckMD5
File "/mnt/Misc/Stalker/env/lib/python3.12/site-packages/launcher/commands/check.py", line 9, in <module>
from launcher.mods import read_mod_maker
File "/mnt/Misc/Stalker/env/lib/python3.12/site-packages/launcher/mods/__init__.py", line 5, in <module>
from launcher.mods.base import Base, Default
File "/mnt/Misc/Stalker/env/lib/python3.12/site-packages/launcher/mods/base.py", line 4, in <module>
from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
```

**Comment by Mord3rca** [comment]
https://github.com/Mord3rca/gamma-launcher?tab=readme-ov-file#modulenotfounderror-no-module-named-distutils
