### ISSUE TITLE
full-install command failure with both suggested prepends on venv install

### ISSUE THREAD

**Issue by helpmeplease234** [Mord3rca/gamma-launcher#138]
**Hi. I'm getting the following log when attempting to run gamma-launcher full-install with the `MAGIC=/usr/share/file/mis/magic.mgc` prepend & with / without --cache-directory on a venv setup:** 

**Using Artix Linux on dinit with the 6.10.2-artix-1 kernel on KDE.**
```
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
    _no_config = getenv('GAMMA_LAUNCHER_NO_CONFIG') is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "launcher/commands/install.py", line 337, in run
  File "launcher/commands/install.py", line 167, in run
    else:
        ^^
  File "launcher/commands/install.py", line 151, in _install_mod_organizer
    if args.gamma_install_mo:
        ^^^^^^^^^^^^^^^^^^^^^^
  File "launcher/archive.py", line 60, in extract_archive
    }
      
  File "magic/__init__.py", line 178, in from_file
  File "magic/__init__.py", line 165, in _get_magic_type
  File "magic/__init__.py", line 73, in __init__
  File "magic/__init__.py", line 332, in magic_load
  File "magic/__init__.py", line 225, in errorcheck_negative_one
magic.MagicException: b"File 5.41 supports only version 16 magic files. `/usr/share/file/misc/magic.mgc' is version 18"
[26288] Failed to execute script 'gamma-launcher' due to unhandled exception!
```

**And with the `LD_PRELOAD=/usr/lib/libmagic.so` prepend:**

```
etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
[+] Installing base setup for GAMMA
  - Using cached Mod.Organizer-2.4.4.7z
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 68, in main
    _no_config = getenv('GAMMA_LAUNCHER_NO_CONFIG') is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "launcher/commands/install.py", line 337, in run
  File "launcher/commands/install.py", line 167, in run
    else:
        ^^
  File "launcher/commands/install.py", line 151, in _install_mod_organizer
    if args.gamma_install_mo:
        ^^^^^^^^^^^^^^^^^^^^^^
  File "launcher/archive.py", line 60, in extract_archive
    }
      
  File "magic/__init__.py", line 178, in from_file
  File "magic/__init__.py", line 165, in _get_magic_type
  File "magic/__init__.py", line 73, in __init__
  File "magic/__init__.py", line 332, in magic_load
  File "magic/__init__.py", line 225, in errorcheck_negative_one
magic.MagicException: b'could not find any valid magic files!'
[27119] Failed to execute script 'gamma-launcher' due to unhandled exception!
```

**Comment by Mord3rca** [comment]
Hey

If PRELOAD did not work for you, do a venv installation of the master branch

https://github.com/Mord3rca/gamma-launcher?tab=readme-ov-file#magic-errors

**Comment by helpmeplease234** [comment]
> Hey
> 
> If PRELOAD did not work for you, do a venv installation of the master branch
> 
> https://github.com/Mord3rca/gamma-launcher?tab=readme-ov-file#magic-errors

Still occurring in a venv, this is the initial issue:
https://files.catbox.moe/izhr78.mp4

**Comment by Mord3rca** [comment]
You are using `./gamma-launcher`, please use `gamma-launcher` instead to use the script from venv.

`command -v gamma-launcher` should return **<path/to/venv>/bin/gamma-launcher**

**Comment by helpmeplease234** [comment]
Making progress. No config file?

```
(env) matthew-artix:[root]:/run/media/matthew/LINUX GAMING/Games/gammalaunch# gamma-launcher full-install --anomaly '/run/media/matthew/LINUX GAMING/Games/anomaly gamma/' --gamma '/run/media/matthew/LINUX GAMING/Games/gamma/' --cache-directory '/run/media/matthew/LINUX GAMING/Games/gammasetup/'

Traceback (most recent call last):
  File "/run/media/matthew/LINUX GAMING/Games/gammalaunch/env/bin/gamma-launcher", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/run/media/matthew/LINUX GAMING/Games/gammalaunch/env/lib/python3.12/site-packages/launcher/cli.py", line 88, in main
    _config_file_path.touch(exist_ok=True)
  File "/usr/lib/python3.12/pathlib.py", line 1303, in touch
    fd = os.open(self, flags, mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/gamma-launcher/config.ini'
```

**Comment by Mord3rca** [comment]
Please do not run as root, this is overkill.

PR #139 please try again on create_config_folder branch

**Comment by helpmeplease234** [comment]
> Please do not run as root, this is overkill.
> 
> PR #139 please try again on create_config_folder branch

Got it working finally, unrelated however I'm getting this error when attempting to run on DX11-AVX:

![Screenshot_20240807_150641](https://github.com/user-attachments/assets/13d9f310-d4cf-481d-8946-d89386e063f2)

**Comment by Mord3rca** [comment]
This is probably a wine setup issue, make sure to follow [this guide](https://github.com/DravenusRex/stalker-gamma-linux-guide?tab=readme-ov-file#okay-you-have-mord3rcas-launcher-set-up-and-ready-to-go-now-what) and try again

**Comment by helpmeplease234** [comment]
> This is probably a wine setup issue, make sure to follow [this guide](https://github.com/DravenusRex/stalker-gamma-linux-guide?tab=readme-ov-file#okay-you-have-mord3rcas-launcher-set-up-and-ready-to-go-now-what) and try again

It was the file permissions primarily. Got everything sorted without hiccup and I'm able to play. Thank you!
