### ISSUE TITLE
psutil errors during full_install

### ISSUE THREAD

**Issue by fonikz** [Mord3rca/gamma-launcher#14]
During full_install I keep getting errors in the same place.

```
[+] Installing mod:  Bizon Replacer
  - Using cached Better_Bizon_Weapon.7.7z
Traceback (most recent call last):
  File "/home/hukt/.local/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 194, in run
    self._install_mods()
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 156, in _install_mods
    self._install_mod(k, v)
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 123, in _install_mod
    extract_archive(file, dir)
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/archive.py", line 10, in extract_archive
    {
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/archive.py", line 11, in <lambda>
    '7z': lambda f, p: SevenZipFile(f).extractall(p),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 963, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 624, in _extract
    self.worker.extract(
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1264, in extract
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1289, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1358, in _extract_single
    crc32 = self.decompress(fp, f.folder, obfp, f.uncompressed, f.compressed, src_end)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1409, in decompress
    max_block_size = get_memory_limit()
                     ^^^^^^^^^^^^^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/properties.py", line 98, in get_memory_limit
    import psutil
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)
```

```
[+] Installing mod:  Bizon Replacer
  - Using cached Better_Bizon_Weapon.7.7z
Traceback (most recent call last):
  File "/home/hukt/.local/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 194, in run
    self._install_mods()
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 156, in _install_mods
    self._install_mod(k, v)
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 123, in _install_mod
    extract_archive(file, dir)
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/archive.py", line 10, in extract_archive
    {
  File "/home/hukt/.local/lib/python3.11/site-packages/launcher/archive.py", line 11, in <lambda>
    '7z': lambda f, p: SevenZipFile(f).extractall(p),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 963, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 624, in _extract
    self.worker.extract(
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1264, in extract
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1289, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1358, in _extract_single
    crc32 = self.decompress(fp, f.folder, obfp, f.uncompressed, f.compressed, src_end)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/py7zr.py", line 1409, in decompress
    max_block_size = get_memory_limit()
                     ^^^^^^^^^^^^^^^^^^
  File "/home/hukt/.local/lib/python3.11/site-packages/py7zr/properties.py", line 102, in get_memory_limit
    avmem = psutil.virtual_memory().available
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'psutil' has no attribute 'virtual_memory'`
```

**Comment by Mord3rca** [comment]
You don't seems to use a venv. Can you retry with one ?

This seems to be a dependency error, what distro are you using ?

For reference, on my venv, psutil is at version 5.9.4

**Comment by fonikz** [comment]
Maybe I did it wrong, never using venv's before. I did create a venv in the folder the launcher is in with `python3 -m venv launcher/`

And then `python3.11 pip install gamma-launcher-master/` to install. Is there a venv-specific command to install or run gamma-launcher after creating the venv?

I'm using Ubuntu Studio 22.04, KDE Plasma 5.24.7

**Comment by Mord3rca** [comment]
You need to create the venv with: `python3 -m <dir>`
Then activate the venv: `. <dir>/bin/activate`

Finally, you install the launcher with pip and dependency should be installed by it.
`pip install <path/to/launcher>`

And now you can use the launcher without error

**Comment by Mord3rca** [comment]
Can you do a `pip list` in the venv ?

**Comment by fonikz** [comment]
Sorry, it was me, changing the directory name borked the venv (it was still named after the old directory). Rebuilding the venv fixed. But now, a new issue on a new mod. I tried the cached version as well as downloading a new copy:

```  - Downloading Agressor_1.0.2.rar
Traceback (most recent call last):
  File "/mnt/instant/Games/stalker/env/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('launcher==0.1', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 194, in run
    self._install_mods()
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 156, in _install_mods
    self._install_mod(k, v)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 123, in _install_mod
    extract_archive(file, dir)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/archive.py", line 10, in extract_archive
    {
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/archive.py", line 12, in <lambda>
    'rar': lambda f, p: RarFile(f).extractall(p),
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/rarfile.py", line 927, in _make_file
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/rarfile.py", line 2197, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=35629 got=0
```

**Comment by fonikz** [comment]
Fixed by installing unrar.

Note that `pip install unrar` was not enough, I had to `apt install unrar`

**Comment by fonikz** [comment]
```[+] Installing mod:  Grass Tweaks (reinstall for different options)
  - Using cached Aydins_Grass_Tweaks_4.0.7z
Traceback (most recent call last):
  File "/mnt/instant/Games/stalker/env/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('launcher==0.1', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 194, in run
    self._install_mods()
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 156, in _install_mods
    self._install_mod(k, v)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 123, in _install_mod
    extract_archive(file, dir)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/archive.py", line 10, in extract_archive
    {
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/archive.py", line 11, in <lambda>
    '7z': lambda f, p: SevenZipFile(f).extractall(p),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 963, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 624, in _extract
    self.worker.extract(
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1204, in extract
    self.extract_single(
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1292, in extract_single
    raise e
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1289, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1358, in _extract_single
    crc32 = self.decompress(fp, f.folder, obfp, f.uncompressed, f.compressed, src_end)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1416, in decompress
    fq.write(tmp)
OSError: [Errno 28] No space left on device```

Now I'm getting this, currently troubleshooting. The device isn't out of space, there's 189GB free. I'll report back what I find.

On that note, MD5 checks out but I do have a couple errors about ```ERROR: 02 - [OPTIONAL] RESHADE SR - Film Reshade/bin do not exist```. That's not the only mod with the error.

**Comment by Mord3rca** [comment]
Launcher will decompress in a tmpdir (located in `/tmp` by default.) this can be change with the env variable **TMPDIR**

**Comment by fonikz** [comment]
```[+] Installing mod:  Grass Tweaks (reinstall for different options)
  - Using cached Aydins_Grass_Tweaks_4.0.7z
Traceback (most recent call last):
  File "/mnt/instant/Games/stalker/env/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('launcher==0.1', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 194, in run
    self._install_mods()
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 156, in _install_mods
    self._install_mod(k, v)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 123, in _install_mod
    extract_archive(file, dir)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/archive.py", line 10, in extract_archive
    {
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/launcher/archive.py", line 11, in <lambda>
    '7z': lambda f, p: SevenZipFile(f).extractall(p),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 963, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 624, in _extract
    self.worker.extract(
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1204, in extract
    self.extract_single(
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1292, in extract_single
    raise e
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1289, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "/mnt/instant/Games/stalker/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1361, in _extract_single
    raise CrcError(crc32, f.crc32, f.filename)
py7zr.exceptions.CrcError: (1250159788, 602651483, "Aydin's Grass Tweaks - WINTER 3.0/gamedata/textures/detail/ground_grass_04.dds")
```

Sometimes it gives me this error instead. Even after changing the tmpdir.

**Comment by fonikz** [comment]
As usual I was doing it wrong. `export TMPDIR=tmp\` and then `echo TMPDIR` to check that it set correctly. It's moving along now.
