### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by LichHunter** [Mord3rca/gamma-launcher#148]
Hi, 
I'm running gamma-launcher on latest master and get this error 
```
[+] Installing base setup for GAMMA
Traceback (most recent call last):
  File "/home/omen/Code/Python/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/omen/Code/Python/gamma-launcher/env/lib/python3.12/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
  File "/home/omen/Code/Python/gamma-launcher/env/lib/python3.12/site-packages/launcher/commands/install.py", line 299, in run
    GammaSetup().run(args)
  File "/home/omen/Code/Python/gamma-launcher/env/lib/python3.12/site-packages/launcher/commands/install.py", line 136, in run
    self._install_mod_organizer(args.mo_version)
  File "/home/omen/Code/Python/gamma-launcher/env/lib/python3.12/site-packages/launcher/commands/install.py", line 119, in _install_mod_organizer
    mo_archive.download(self._cache_dir or dir, use_cached=True)
  File "/home/omen/Code/Python/gamma-launcher/env/lib/python3.12/site-packages/launcher/mods/downloader/base.py", line 31, in download
    self._archive = self._archive or (to / basename(urlparse(self._url).path))
                                      ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

Command used to run gamma:
`$ gamma-launcher full-install --anomaly /home/omen/Games/stalker-gamma/drive_c/anomaly --gamma /home/omen/Games/stalker-gamma/drive_c/gamma`

If you need any more info, will gladly provide
Thank you

**Comment by Mord3rca** [comment]
Hey, can you give it another shot ? Thanks !

**Comment by LichHunter** [comment]
Yeap, seems to work just fine now
Thank you
