### ISSUE TITLE
[Endeavour OS] Gamma-Launcher failes to write modpack files

### ISSUE THREAD

**Issue by GingerBobRoss** [Mord3rca/gamma-launcher#166]
I reinstalled Gamma-launcher through Yay and I am running into issues with updating my gamma install as my game is currently corrupted and crashes.
When running `gamma-launcher full-install --gamma "/mnt/Linux-Storage/Steam/steamapps/common/STALKER-GAMMA/GAMMA"` i get the following error message below.
I doublechecked Gamma.git and was able to clone it without any issue

I also get this error using the Stand-alone launcher from the latest release

```sh
[gonger@Gonger-Endeavour ~]$ gamma-launcher full-install --gamma "/mnt/Linux-Storage/Steam/steamapps/common/STALKER-GAMMA/GAMMA"
[+] Installing base setup for GAMMA
  - Downloading Mod.Organizer-2.4.4.7z: 85.9MiB [00:01, 55.8MiB/s]
Extracting /tmp/gamma-launcher-mo-setup-b6gyz31m/Mod.Organizer-2.4.4.7z
    Fetching remote Grokitach from gamma_setup.git...
Traceback (most recent call last):
  File "/usr/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('gamma-launcher==2.0', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 296, in run
    GammaSetup().run(args)
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 131, in run
    archive.extract(self._grok_mod_dir, "gamma_setup-*")
  File "/usr/lib/python3.12/site-packages/launcher/mods/downloader/github/git.py", line 35, in extract
    repo.git().execute(['git', 'worktree', 'add', '--detach', str(pdir), f'{user}/main'])
  File "/usr/lib/python3.12/site-packages/git/cmd.py", line 1183, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git worktree add --detach /tmp/gamma-launcher-github-extract-wduoc_dk Grokitach/main
  stderr: 'Preparing worktree (detached HEAD cb58077)
error: unable to write file modpack_patches/bin/AnomalyDX11AVX.exe
error: unable to write file modpack_patches/bin/AnomalyDX8.exe
error: unable to write file modpack_patches/bin/AnomalyDX8AVX.exe
error: unable to write file modpack_patches/bin/AnomalyDX9.exe
error: unable to write file modpack_patches/bin/AnomalyDX9AVX.exe
error: unable to write file modpack_patches/bin/G.A.M.M.A.Reshade.ini
error: unable to write file modpack_patches/bin/ReShade.ini
error: unable to write file modpack_patches/bin/alsoft.ini
error: unable to write file modpack_patches/bin/alsoft.ini.back
error: unable to write file modpack_patches/bin/dxgi.dll
error: unable to write file modpack_patches/bin/dxgi.log
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/AmbientLight.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/Blending.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/Daltonize.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/Deband.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/DisplayDepth.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/DrawText.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/LUT.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/Macros.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_00_Base_Effects.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_00_Blend_Modes.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_00_Color_Spaces.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_00_Noise_Samplers.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_01A_RT_Correct_Contrast.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_01B_RT_Correct_Color.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_01_Color_Gamut.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_02_Bloom.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_02_Bonus_LUT_pack.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_02_Cinetools_LUT.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_02_LUT_Creator.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_03_Color_Space_Curves.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_03_Curved_Levels.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_03_Filmic_Adaptation.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_03_Levels.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_03_Shadows_Midtones_Highlights.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_BlacknWhite.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Color_Balance.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Color_Gradients.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Color_Isolation.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Color_Temperature.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Contrast_Brightness_Saturation.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Magical_Rectangle.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Saturation_Limit.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Selective_Color.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Selective_Color_v2.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_04_Technicolor.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_05_Sharpening.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_06_Chromatic_Aberration.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_06_Depth_Slicer.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_06_Film_Grain.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_06_Luma_Fade.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_06_Posterize_Pixelate.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/PD80/PD80_LUT_v2.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/ReShade.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/ReShadeUI.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/TriDither.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/UIMask.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_bloom.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_common.fxh
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_deband.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_dof.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_lightroom.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_mxao.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_sharp.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Shaders/qUINT/qUINT_ssr.fx
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/ArcaneBloom_Dirt.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/AreaTex.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/AspectRatio.jpg
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/DigitMap.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Dirt.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/DirtA.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/DirtOVB.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/DirtOVR.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/FontAtlas.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Layer.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/LensDB.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/LensDB2.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/LensDOV.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/LensDUV.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/LensSprite.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/MagicBloom_Dirt.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/MatCap.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/MultiLut_atlas1.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/NeoBloom_LensDirt.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/NormalMap.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Overlay.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Pong.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/SearchTex.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Sketch_Shadow.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Stage.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/Stageplus.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/UIDetectMaskRGB.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/UIMask.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/alpha-checkerboard.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/bayer16x16.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/cursor.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/depthmap.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/fognoise.jpg
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/image.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/lut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/lut_neutral_cine.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/lut_neutral_cine_v2.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/monochrome_gaussnoise.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/neutral_lut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_bluenoise.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_bluenoise_rgba.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_cinelut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_clean_lut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_example-lut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_gaussnoise.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_neutral-lut.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/pd80_permtexture.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/ssdonoise.png
error: unable to write file modpack_patches/bin/reshade-shaders/Textures/waow.png
error: unable to write file modpack_patches/bin/soft_oal.dll
error: unable to write file modpack_patches/bin/soft_oal.dll.back
Updating files: 100% (6757/6757), done.
fatal: Could not reset index file to revision 'HEAD'.'
```

Edit: Puting output in a code block, removing output of `update-gamma` since redondent & alias not known (probably the same)

**Comment by Mord3rca** [comment]
Hey,

You need 9G in TMPDIR to checkout gama_setup.git. Increase TMPDIR size and try again.
More info here: #154

**Comment by Mord3rca** [comment]
#168 should resolve this (and TMPDIR with +9G available). Can you try ?
