### ISSUE TITLE
SSL CertVerification Error 

### ISSUE THREAD

**Issue by kuro-linlin** [Mord3rca/gamma-launcher#179]
My System:

- Nobara Linux 40 (fedora fork)
- Linux 6.11.9-200
- KDE Plasma 6.2.2

I tried to full install with the following command

`
./gamma-launcher full-install --anomaly Anomaly --gamma Gamma
`

And I got this output.

```
❯ ./gamma-launcher full-install --anomaly Anomaly --gamma Gamma
[+] Installing base Anomaly 1.5.3
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "urllib3/connectionpool.py", line 1095, in _validate_conn
  File "urllib3/connection.py", line 730, in connect
  File "urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "cloudscraper/__init__.py", line 100, in wrap_socket
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1104, in _create
  File "ssl.py", line 1382, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 789, in urlopen
  File "urllib3/connectionpool.py", line 490, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 667, in send
  File "urllib3/connectionpool.py", line 843, in urlopen
  File "urllib3/util/retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.moddb.com', port=443): Max retries exceeded with url: /downloads/start/277404 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gamma-launcher.py", line 8, in <module>
  File "launcher/cli.py", line 113, in main
  File "launcher/commands/install.py", line 291, in run
  File "launcher/commands/install.py", line 63, in run
  File "launcher/mods/downloader/moddb.py", line 97, in download
  File "launcher/mods/downloader/moddb.py", line 47, in _get_download_url
  File "requests/sessions.py", line 602, in get
  File "cloudscraper/__init__.py", line 259, in request
  File "cloudscraper/__init__.py", line 192, in perform_request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.moddb.com', port=443): Max retries exceeded with url: /downloads/start/277404 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
[PYI-36517:ERROR] Failed to execute script 'gamma-launcher' due to unhandled exception!

```

**Comment by Mord3rca** [comment]
Hey ! Multiple solutions here:

* Your ModDB mirror is kinda fucked up

* You don't have the authority CA to verify it on your machine

* You are behind a naughty HTTPS proxy

Try to fetch the page on your browser, use pip installation to make sure to use CA certs of your system.

Note: Self exec are made for Ubuntu systems and may not be 100% compatible with other distrib.
