### ISSUE TITLE
IsADirectoryError on mod Catspaw_Milspec_PDA-1.14.1

### ISSUE THREAD

**Issue by bndlfm** [Mord3rca/gamma-launcher#181]
I think this is a path issue with weird mod naming conventions but I'm not much of a programmer.

Could be because I'm running the python script in a podman container? Wouldn't make much sense.

If you're wondering why I'm running it in a container, it's because I'm a fool (NixOS). I plan to copy the files over to my host afterwards.

```

Calculating hash of Catspaw_Milspec_PDA-1.14.1.zip: 100%|##################################| 768k/768k [00:00<00:00, 301MiB/s]
[+] Installing mod: Milspec PDA
Extracting /home/bazz/STALKER_GAMMA/downloads/Catspaw_Milspec_PDA-1.14.1.zip
Traceback (most recent call last):
  File "/usr/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/cli.py", line 113, in main
    args.cobject().run(args)
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 304, in run
    self._install_mods()
  File "/usr/lib/python3.12/site-packages/launcher/commands/install.py", line 253, in _install_mods
    mod.install(self._mod_dir)
  File "/usr/lib/python3.12/site-packages/launcher/mods/installer/default.py", line 68, in install
    with DefaultTempDir(self, prefix="gamma-launcher-modinstall-") as pdir:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/launcher/mods/tempfile.py", line 49, in __enter__
    getattr(self, hotfix)(s)
  File "/usr/lib/python3.12/site-packages/launcher/mods/tempfile.py", line 33, in _post_decompression_hotfix_00_malformed_archive
    path.rename(dir / p)
  File "/usr/lib/python3.12/pathlib.py", line 1363, in rename
    os.rename(self, target)
IsADirectoryError: [Errno 21] Is a directory: '/tmp/gamma-launcher-modinstall-0xdjvtpb/02. Legacy Non-DLTX Mapspots and Crafting (DO NOT use with GAMMA or other modded exes)\\gamedata\\' -> '/tmp/gamma-launcher-modinstall-0xdjvtpb/02. Legacy Non-DLTX Mapspots and Crafting (DO NOT use with GAMMA or other modded exes)/gamedata'
```

**Comment by easymod0** [comment]
I get the same error on a fresh install. I believe the issue is the archive that is downloaded is corrupt on linux somehow. If I download on windows, unzip and re-archive it using 7zip I can correctly open it on linux. However even if I replace the file downloaded, the script checks the hash value and re-downloads the corrupt archive.

The other Catspaw mods have the same issue for me on Arch. Attached what the archive looks like, it seems like all the folders are recognized as files. I don't know how to get around this. If there is an option to not check the hash value and re-download the mods if they exist, that would allow us to get around this manually at least. Does  this option exist??

![image](https://github.com/user-attachments/assets/6199905d-d419-487d-a99d-f6b1803ad259)

**Comment by easymod0** [comment]
Also instead of skipping hash check and not downloading archive files that exist, another workaround would add some command line options to skip specific mods from the full-install command. If we can skip these catspaw mods and install them manually ourselves that would also help out here.

**Comment by Mord3rca** [comment]
Which version are you using ?

Looks like #176 which was fixed if your are using master branch.

**Comment by easymod0** [comment]
I am using the latest release 2.1, I will test out building from source and using master branch

**Comment by easymod0** [comment]
Yep that did the trick for me, thanks a ton

**Comment by hitagi78** [comment]
Sorry for mentioning this but i think this is related. I have this problem, I'm using main branch w/ pip.

![image](https://github.com/user-attachments/assets/af61cc7d-7a7b-46c7-9ae0-2aa3f6b906af)

**Comment by Mord3rca** [comment]
Not related.

Was **/home/dev/stalker/gamma** empty before running the launcher ?
Can you do a `ls /home/dev/stalker/gamma` ?

**Comment by hitagi78** [comment]
> Not related.
> 
> Was **/home/dev/stalker/gamma** empty before running the launcher ? Can you do a `ls -l /home/dev/stalker/gamma` ?

yeah you're right its leftover from downloading attempt before.  Still trying to make 0.9.3 works :D.

Thanks
