### ISSUE TITLE
Full Install don't work

### ISSUE THREAD

**Issue by jptrzy** [Mord3rca/gamma-launcher#20]
I don't know what had happened, but here are my logs:  

```
$ gamma-launcher full-install --anomaly Anomaly --gamma GAMMA
[+] Updating G.A.M.M.A. definition
[+] Reading GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
[+] Installing mod:  Dux Characters Kit Voices Pack
  - Using cached Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
    Installing Dux's Innumerable Character Kit Voices Pack -> GAMMA/mods/305- Dux Characters Kit Voices Pack - Demonized
    Installing Dux's Innumerable Character Kit Voices Pack English ISG -> GAMMA/mods/305- Dux Characters Kit Voices Pack - Demonized
[+] Installing mod:  Grulag's Dead Bushes
  - Using cached gamma_large_files_v2.zip
    Installing gamma_large_files_v2-main/Grulag's Dead Bushes -> GAMMA/mods/272- Grulag's Dead Bushes - Grulag
[+] Installing mod:  Headlamp Animation Fix
  - Using cached HeadlampAnimationFix.3.zip
    Installing HeadlampAnimationFix -> GAMMA/mods/270- Headlamp Animation Fix - RavenAscendant
[+] Installing mod:  Safe Areas Transitions
  - Using cached Safe_Start_2.2.zip
[+] Installing mod:  Zone Customization Project (ZCP)
  - Using cached zone_customization_project_1.5e.zip
[+] Installing mod:  Hideout Furniture
  - Using cached HideoutFurniture-v2.1.0.zip
    Installing 00 Main -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 001 Dependencies/ahuyn -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 001 Dependencies/arm -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 10 Nomad Module/11 Stash Containers -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 10 Nomad Module/12 Portable Lights -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31 Weapon Displays -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.3 VSSK Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.2 PPP Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.1 AUGmented Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.5 Bizon Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.6 Vityaz Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.7 G36 Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.8 Saiga-12K Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.9 SVD Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.10 AN-94 Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 30 Fortress Module/31.0 Patches/31.11 KAR Patch -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 40 Homestead Module/41 Portable Workshop -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 50 Fun Module/51 Piano -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 50 Fun Module/52 Radio -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 50 Fun Module/52.0 Other Stations/52.1 Anomaly Radios Extended -> GAMMA/mods/245- Hideout Furniture - Aoldri
    Installing 90 Addons/91 Stash Capacities -> GAMMA/mods/245- Hideout Furniture - Aoldri
[+] Installing mod:  Weird Tasks Framework
  - Using cached WTF_3.6.zip
    Installing Weird_Tasks_Framework -> GAMMA/mods/244- Weird Tasks Framework - Igigog
[+] Installing mod:  Bizon Replacer
  - Using cached Better_Bizon_Weapon.7.7z
[+] Installing mod:  Xenotech Protects Cordon Base
  - Using cached Combat_Behavior_1.02.4.rar
Traceback (most recent call last):
  File "/home/jp3/.local/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jp3/.local/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/home/jp3/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 194, in run
    self._install_mods()
  File "/home/jp3/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 156, in _install_mods
    self._install_mod(k, v)
  File "/home/jp3/.local/lib/python3.11/site-packages/launcher/commands/install.py", line 123, in _install_mod
    extract_archive(file, dir)
  File "/home/jp3/.local/lib/python3.11/site-packages/launcher/archive.py", line 10, in extract_archive
    {
  File "/home/jp3/.local/lib/python3.11/site-packages/launcher/archive.py", line 12, in <lambda>
    'rar': lambda f, p: RarFile(f).extractall(p),
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp3/.local/lib/python3.11/site-packages/rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp3/.local/lib/python3.11/site-packages/rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jp3/.local/lib/python3.11/site-packages/rarfile.py", line 927, in _make_file
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/jp3/.local/lib/python3.11/site-packages/rarfile.py", line 2197, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=3178 got=51
```

**Comment by Mord3rca** [comment]
Hello, please delete **Combat_Behavior_1.02.4.rar** in your downloads folder and try again

**Comment by Mord3rca** [comment]
You can now use **check-md5** with option `--redownload` to force the cache to be updated.

`gamma-launcher check-md5 --gamma <path/to/gamma> --redownload`
