### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by axet** [Mord3rca/gamma-launcher#22]
Hello!

`pip install .`

does not install all dependencies. I have to run:

`pip install bs4 requests tenacity rarfile py7zr`

and

`sudo  apt install python3.11-venv`

**Comment by Mord3rca** [comment]
Hello,

Can you put logs of `pip install .` ? Was it done in a venv ?
What was the error ?

**Comment by axet** [comment]
Sure venv. No errors. launcher probably has missing dependencies block.

```
$ pip install .
Processing /media/axet/128GB/S.T.A.L.K.E.R. GAMMA/gamma-launcher
  Preparing metadata (setup.py) ... done
Installing collected packages: launcher
  DEPRECATION: launcher is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for launcher ... done
Successfully installed launcher-0.1
```

**Comment by Mord3rca** [comment]
Can you try again with the PR above ? This should fix the issue

**Comment by axet** [comment]
Thanks. It works.

**Comment by axet** [comment]
It saying it has missing metadata and I unable to install it.

'No package metadata was found for launcher'

```
 pip install metadata
Collecting metadata
  Downloading metadata-0.2.tar.gz (1.5 kB)
  Preparing metadata (setup.py) ... done
  Downloading metadata-0.1.1.tar.gz (1.5 kB)
  Preparing metadata (setup.py) ... done
  Downloading metadata-0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
ERROR: Cannot install metadata==0.1, metadata==0.1.1 and metadata==0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    metadata 0.2 depends on hachoir-core==1.3.3
    metadata 0.1.1 depends on hachoir-core==1.3.3
    metadata 0.1 depends on hachoir-core==1.3.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by Mord3rca** [comment]
Can you print the error message regarding metadata dependency ?

On my side, it is not installed and not required (python-3.11)

**Comment by axet** [comment]
```
gamma-launcher full-install --anomaly /media/axet/128GB/S.T.A.L.K.E.R.\ GAMMA/Anomaly/  --gamma /media/axet/128GB/S.T.A.L.K.E.R.\ GAMMA/GAMMA/
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/axet/128GB/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('launcher==0.1', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/axet/128GB/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/bin/gamma-launcher", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for launcher
```

**Comment by axet** [comment]
I got it. system python can not be used...
