### ISSUE TITLE
False-negative for 'brotlicffi'" and "cannot import 'file_digest'"

### ISSUE THREAD

**Issue by Kosiare** [Mord3rca/gamma-launcher#29]
Yo,
Steps I did:
1. Download v1.0 release
2. `chmod +x gamma-launcher`

Checking md5:
```
❯ ./gamma-launcher check-md5 --gamma GAMMA/
Traceback (most recent call last):
  File "py7zr/compressor.py", line 67, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "brotli.py", line 8, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEIdg8WeT/libstdc++.so.6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gamma-launcher", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "launcher/cli.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "launcher/commands/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "launcher/commands/install.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "launcher/archive.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "py7zr/__init__.py", line 45, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "py7zr/py7zr.py", line 43, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "py7zr/archiveinfo.py", line 36, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "py7zr/compressor.py", line 69, in <module>
ModuleNotFoundError: No module named 'brotlicffi'
[2258208] Failed to execute script 'gamma-launcher' due to unhandled exception!

❯ pip3 list | grep brotlicffi
brotlicffi         1.0.9.2
```

Trying to use a package built by myself:

1. `python3 -m venv gamma_venv`
3. `source gamma_venv/bin/activate`
4. `pip3 install --upgrade pip`
5. `cd anomaly-gamma/ && pip3 install .`

At first glance, it installs without problems, and no errors are found. But whenever I call `gamma-launcher` I got this error:
Checking md5:
```
❯ gamma-launcher check-md5 --gamma GAMMA
Traceback (most recent call last):
  File "/home/<my-username>/.local/bin/gamma-launcher", line 5, in <module>
    from launcher.cli import main
  File "/home/<my-username>/.local/lib/python3.10/site-packages/launcher/cli.py", line 2, in <module>
    from launcher.commands import (
  File "/home/<my-username>/.local/lib/python3.10/site-packages/launcher/commands/__init__.py", line 1, in <module>
    from .check import CheckMD5
  File "/home/<my-username>/.local/lib/python3.10/site-packages/launcher/commands/check.py", line 1, in <module>
    from hashlib import file_digest
ImportError: cannot import name 'file_digest' from 'hashlib' (/usr/lib/python3.10/hashlib.py)
```

Trying to do the full install:
```
❯ gamma-launcher full-install --anomaly Anomaly/ --gamma GAMMA/
Traceback (most recent call last):
  File "/home/<my-username>/.local/bin/gamma-launcher", line 5, in <module>
    from launcher.cli import main
  File "/home/<my-username>/.local/lib/python3.10/site-packages/launcher/cli.py", line 2, in <module>
    from launcher.commands import (
  File "/home/<my-username>/.local/lib/python3.10/site-packages/launcher/commands/__init__.py", line 1, in <module>
    from .check import CheckMD5
  File "/home/<my-username>/.local/lib/python3.10/site-packages/launcher/commands/check.py", line 1, in <module>
    from hashlib import file_digest
ImportError: cannot import name 'file_digest' from 'hashlib' (/usr/lib/python3.10/hashlib.py)
```

Confirmation that I'm using *venv*:
```
❯ which python
/mnt/ssd/anomaly-gamma/gamma_venv/bin/python
❯ which python3
/mnt/ssd/anomaly-gamma/gamma_venv/bin/python3
```

Python version
```
❯ python3 --version
Python 3.10.6
```

**Comment by Mord3rca** [comment]
Hello,

`file_digest` is python 3.11 only, can you try again with the branch [fix/python10](https://github.com/Mord3rca/gamma-launcher/tree/fix/python10)

Regarding the executable ... It seems to be caused by a libc error. I'll try to make it static or contain libc.

**Comment by Kosiare** [comment]
Switching to [fix/python10](https://github.com/Mord3rca/gamma-launcher/tree/fix/python10) helped me right away. Sorry that I didn't check other branches before creating an issue. I didn't test the installation yet but at least `check-md5` has worked for me.
I'll reopen this issue if I'll encounter another related problem.
