### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by evfeal** [Mord3rca/gamma-launcher#45]
`./gamma-launcher full-install --anomaly ~/Games/S.T.A.L.K.E.R.\ Anomaly/ --gamma ~/Games/S.T.A.L.K.E.R.\ Gamma/
[+] Updating G.A.M.M.A. definition
Traceback (most recent call last):
  File "gamma-launcher", line 8, in <module>
  File "launcher/cli.py", line 64, in main
  File "launcher/commands/install.py", line 202, in run
  File "launcher/commands/install.py", line 71, in _update_gamma_definition
  File "launcher/archive.py", line 10, in extract_archive
  File "launcher/archive.py", line 13, in <lambda>
  File "zipfile.py", line 1301, in __init__
  File "zipfile.py", line 1368, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
[9210] Failed to execute script 'gamma-launcher' due to unhandled exception!`

the same thing happens whether in a venv or not,
system is Void Linux

**Comment by Mord3rca** [comment]
`md5sum ~/Games/S.T.A.L.K.E.R.\ Gamma/.Grok\'s\ Modpack\ Installer/GAMMA_definition.zip` ?

For reference: **035ed0e5ae5baa07c5dfb8521f953053** - based on https://github.com/Grokitach/Stalker_GAMMA/commit/a5ac120fabd0622f55f379b7d842f77a251f3ae7

**Comment by evfeal** [comment]
just checked and i do get a different md5, does this mean i should redownload?

**Comment by Mord3rca** [comment]
Delete file & try again. If it does not work:
* download it via your browser
* Exact it and copy `Stalker_GAMMA-main/*` to Grok directory
* Run `full-install` with `--no-def-update`

**Comment by Mord3rca** [comment]
Did you managed to get this running ? (via the workaround or by trying another time)

**Comment by Mord3rca** [comment]
No user input, closing as won't do

**Comment by InsaneCake** [comment]
Have encoutered same issue.
Can confirm that just deleting `gamma/.Grok's Modpack Installer/GAMMA_definition.zip` works.
