### ISSUE TITLE
Error when using check-md5 command 

### ISSUE THREAD

**Issue by KarthikScoprion** [Mord3rca/gamma-launcher#49]
I have this error popping up when i use the "check-md5 -- gamma" command and the same issue when I try to do a full install.
I am unsure whether this error pops up only to me or it is the same for everyone.
I also use Linux if that help (Arch linux).

`
[+] Reading /home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & 

/home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...

Traceback (most recent call last):

  File "/home/karthik/gamma-launcher /gamma-launcher/env/bin/gamma-launcher", line 10, in <module>
    sys.exit(main())
             ^^^^^^

  File "/home/karthik/gamma-launcher /gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main

    args.cobject().run(args)
  File "/home/karthik/gamma-launcher /gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/check.py", line 70, in run
    mod_maker = read_mod_maker(
                ^^^^^^^^^^^^^^^
  
File "/home/karthik/gamma-launcher /gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/common.py", line 41, in read_mod_maker
    mods_make = _read_mod_list(mod_list)
                ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/karthik/gamma-launcher /gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/common.py", line 32, in _read_mod_list
    with open(mod_list) as f:
         ^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: "/home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt"
`

![image](https://github.com/Mord3rca/gamma-launcher/assets/87354724/e293adeb-2147-4002-acba-7567fc8c059a)

**Comment by Mord3rca** [comment]
Hello,

Check MD5 assume you already have installed ModOrganizer G.A.M.M.A.'s profile and go for modlist from there. It's maybe more logical to use modlist from definition .... so you can check-md5 and update download cache before an installation.

**Comment by KarthikScoprion** [comment]
Hey, 
I tried running the `full-install` command and it throws this error:

`gamma-launcher full-install --anomaly ~/Anomaly  --gamma ~/Gamma

[+] Updating G.A.M.M.A. definition

    downloading archive...

Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^

  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)

  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 204, in run
    self._update_gamma_definition()

  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 68, in _update_gamma_definition
    g.download(gdef)

  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/downloader/base.py", line 34, in download
    with open(path, 'wb') as f:
         ^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: "/home/karthik/Gamma/.Grok's Modpack Installer/GAMMA_definition.zip"`

I also tried running it in a VM it still does not work.

**Comment by Mord3rca** [comment]
Is **/home/karthik/Gamma/.Grok's Modpack Installer/** folder exist ?

**Comment by KarthikScoprion** [comment]
> Is **/home/karthik/Gamma/.Grok's Modpack Installer/** folder exist ?

Hey,
Only `/home/karthik/Gamma` Exists. 
There is no Folder called .`Grok's Modpack Installer`

**Comment by Mord3rca** [comment]
Oh ! I see now, you need to follow this [guide](https://github.com/DravenusRex/stalker-gamma-linux-guide) for the first setup.

You should have a working Anomaly install & decompress **GAMMA RC3.7z** in Gamma directory.

**Comment by KarthikScoprion** [comment]
Oh I get it now, I guess I overlooked that step..
So yeah thank you very much, and also where do i get the `GAMMA RC3.7z`  from?

**Comment by Mord3rca** [comment]
You have to go on Discord or use on of these mirror links: https://www.gamepressure.com/newsroom/stalker-gamma-install-guide/z44b9e

**Comment by KarthikScoprion** [comment]
Oh alright.. And also Thank you very much for your time... :)
