### ISSUE TITLE
Full-Install Error 

### ISSUE THREAD

**Issue by KarthikScoprion** [Mord3rca/gamma-launcher#51]
Hey,
I came across this error when trying to install GAMMA. It throws the error whenever I try to run the full install command.
This error is the same error from post #20 but even though I try the given your solution it wont work

Here is the error which pops up when I run the command `gamma-launcher full-install --anomaly ~/Anomaly --gamma ~/Gamma`

```shell
gamma-launcher full-install --anomaly ~/Anomaly --gamma ~/Gamma
[+] Updating G.A.M.M.A. definition
[+] Reading /home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & /home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
[+] Installing mod:  Dux Characters Kit Voices Pack
  - Using cached Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
    Installing Dux's Innumerable Character Kit Voices Pack -> /home/karthik/Gamma/mods/305- Dux Characters Kit Voices Pack - Demonized
    Installing Dux's Innumerable Character Kit Voices Pack English ISG -> /home/karthik/Gamma/mods/305- Dux Characters Kit Voices Pack - Demonized
[+] Installing mod:  Grulag's Dead Bushes
  - Using cached gamma_large_files_v2.zip
    Installing Grulag's Dead Bushes -> /home/karthik/Gamma/mods/272- Grulag's Dead Bushes - Grulag
[+] Installing mod:  Headlamp Animation Fix
  - Using cached HeadlampAnimationFix.3.zip
    Installing HeadlampAnimationFix -> /home/karthik/Gamma/mods/270- Headlamp Animation Fix - RavenAscendant
[+] Installing mod:  Safe Areas Transitions
  - Using cached Safe_Start_2.2.zip
[+] Installing mod:  Zone Customization Project (ZCP)
  - Using cached zone_customization_project_1.5e.zip
[+] Installing mod:  Hideout Furniture
  - Using cached HideoutFurniture-v2.1.1.zip
    Installing 00 Main -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing ahuyn -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing arm -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 11 Stash Containers -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 12 Portable Lights -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31 Weapon Displays -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.3 VSSK Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.2 PPP Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.1 AUGmented Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.5 Bizon Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.6 Vityaz Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.7 G36 Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.8 Saiga-12K Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.9 SVD Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.10 AN-94 Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 31.11 KAR Patch -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 41 Portable Workshop -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 51 Piano -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 52 Radio -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 52.1 Anomaly Radios Extended -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
    Installing 91 Stash Capacities -> /home/karthik/Gamma/mods/245- Hideout Furniture - Aoldri
[+] Installing mod:  Weird Tasks Framework
  - Using cached WTF_3.6.zip
    Installing Weird_Tasks_Framework -> /home/karthik/Gamma/mods/244- Weird Tasks Framework - Igigog
[+] Installing mod:  Bizon Replacer
  - Using cached Better_Bizon_Weapon.7.7z
[+] Installing mod:  Xenotech Protects Cordon Base
  - Using cached Combat_Behavior_1.02.4.rar
Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 208, in run
    self._install_mods()
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 170, in _install_mods
    self._install_mod(k, v)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 137, in _install_mod
    extract_archive(file, dir)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/archive.py", line 50, in extract_archive
    _extract_func_dict.get(ext)(filename, path)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/archive.py", line 43, in <lambda>
    'rar': lambda f, p: RarFile(f).extractall(p),
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/rarfile.py", line 927, in _make_file
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^

  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/rarfile.py", line 2197, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=3178 got=51
``` 

Here is the error when I try to run `--redownload` command

```shell
gamma-launcher check-md5 --gamma ~/Gamma  --redownload
[+] Reading /home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & /home/karthik/Gamma/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
-- Starting MD5 Check
Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip (b1832fdb14a1d09c47e0347a454885f7): OK
HeadlampAnimationFix.3.zip (bb831ab253b7ad6d2c98fd6446a6c4f3): OK
Safe_Start_2.2.zip (6df23d10e224487c615ac6c90810bc98): OK
zone_customization_project_1.5e.zip (f8e04367a4439224af7322b6bc1c8e59): OK
HideoutFurniture-v2.1.1.zip (460666193be410c4b2cb12b805afe7e8): OK
WTF_3.6.zip (b16da5b835d2713e8c71bba1059b9e8a): OK
Better_Bizon_Weapon.7.7z (f7c758972d4baae140e3053fffd85d0d): OK
Combat_Behavior_1.02.4.rar (64a832bba2e8b07322345cca32125d36): OK
More_Aggressive_NPC_Looting.1.zip (72471b5cd7bb59a1b2e50a04da5cded3): OK
Monster_Unstucker.3.zip (8a273ea743813117e557a1a3a161a09b): OK
Russian_Localization_RC3.1.7z (f7774318d256765282b9d36b1b02f377): OK
No-sortingNPC_Loot_Claim-Continued.-v1.0.6.2-Bugfix.rar (83a7399f1f06407a6cad6ac1631984c8): OK
HTS_bars_1.01.zip (616af8b3f62d09212fae160393a85440): OK
nomorecompanionfriendlyfireu.zip (153b7faa1a794e1afc4ed012eafc3d52): OK
ArszisMutantBleeding2_0_1.zip (901719be674c136993ecf9dc2994c70a): OK
Lsz.8.zip (d8b83e17764bc9bf6cab757576d1b8a3): OK
companion_tweaks.1.zip (047d353151896ab2a10b7366444b3370): OK
BountySquadsExpanded_1_0_6.7z (1bfe4d2d104096fad3da282cfb05846f): OK
Agressor_1.0.2.rar (a33d497fb11cdf92b3a543f24b728e77): OK
TBs_Angry_Chimera_Growls_v1.1.zip (d75bfd0186c82fcdd3e407a3b737be89): OK
GAMMA_Massive_Text_Overhaul_Project_GMTOP_v1.4.3.1.zip (f9911280b05a33bd19b5a4c07b0edd9b): OK
Atmospherics_GAMMA_1.84.5.7z (dc6680da492b4a72dbcf921d81c709b5): OK
  - Downloading ScreenSpaceShaders_Update16.zip
ScreenSpaceShaders_Update16.zip (fefc30c8d81a59883906d52fde5f34af): OK
  - Downloading Enhanced_Shaders_Color_Grading_1.10.zip
Enhanced_Shaders_Color_Grading_1.10.zip (2a9eae523b89ef70cc1522cda4cf3f30): OK
  - Downloading Beefs_NVGs.1.zip
Beefs_NVGs.1.zip (4d6a11b2aef180b990452053144b9b2e): OK
  - Downloading Aydins_Grass_Tweaks_4.0.7z
Aydins_Grass_Tweaks_4.0.7z (46c1245d066d9926c0885ce48f4db0ad): OK
  - Downloading Dark_signal_blowout_and_anomalies_audio.rar
  -> Failed, retrying...
  - Downloading Dark_signal_blowout_and_anomalies_audio.rar
  -> Failed, retrying...
  - Downloading Dark_signal_blowout_and_anomalies_audio.rar
  -> Failed, retrying...
Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/downloader/__init__.py", line 30, in download_mod
    e.download(file)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/downloader/base.py", line 35, in download
    r = g_session.get(self._url)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/downloader/__init__.py", line 34, in download_mod
    raise TryAgain
tenacity.TryAgain

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karthik/gamma-launcher/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/check.py", line 93, in run
    self._if_file_missing(file, i['url'], hash)
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/check.py", line 60, in _if_file_missing
    file = download_mod(url, self._dl_dir, use_cached=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karthik/gamma-launcher/gamma-launcher/env/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f79c8c4af10 state=finished raised TryAgain>]
```

As, you can see more mods get downloaded when i run `--redownload` but wont work with `full-install`.

**Comment by Mord3rca** [comment]
Archive **Combat_Behavior_1.02.4.rar** is probably corrupted. Can you check if you can `unrar` it manually ? If not, delete it.

For `check-md5` error, use branch for PR #43 , it should ignore error and continue updating download cache.

**Comment by KarthikScoprion** [comment]
> Archive **Combat_Behavior_1.02.4.rar** is probably corrupted. Can you check if you can `unrar` it manually ? If not, delete it.
> 
> For `check-md5` error, use branch for PR #43 , it should ignore error and continue updating download cache.

Hey, Where do i find the **Combat_Behavior_1.02.4.rar** file?

**Comment by Mord3rca** [comment]
Yup, all normal.
You can do a `full-install` now, since download cache is complete

**Comment by Mord3rca** [comment]
Well ... gonna need some info:
`pip list | grep rarfile`
`unrar | grep UNRAR`

**Comment by KarthikScoprion** [comment]
The result of ``pip | list grep rarfile``

```script
pip list | grep rarfile
rarfile            4.0
```

Result of ``unrar | grep UNRAR``
```script
UNRAR 6.22 freeware      Copyright (c) 1993-2023 Alexander Roshal
```

**Comment by Mord3rca** [comment]
Also, `md5sum ~/GAMMA/downloads/Combat_Behavior_1.02.4.rar`
for reference, hash on my side is: **64a832bba2e8b07322345cca32125d36**

**Comment by KarthikScoprion** [comment]
When i run ``md5sum ~/GAMMA/downloads/Combat_Behavior_1.02.4.rar`` it gives this md5sum: 

```script
/home/karthik/GAMMA/downloads/Combat_Behavior_1.02.4.rar: No such file or directory
```

**Comment by Mord3rca** [comment]
`md5sum ~/Gamma/downloads/Combat_Behavior_1.02.4.rar` ?

**Comment by KarthikScoprion** [comment]
> `md5sum ~/Gamma/downloads/Combat_Behavior_1.02.4.rar` ?

Yes looks like when i deleted the file it is not showing up anymore

**Comment by Mord3rca** [comment]
Can you redo a `full-install` and check md5sum of the file if it fails again ?

**Comment by KarthikScoprion** [comment]
Ok the error went away thank you very much
