### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by aryphy** [Mord3rca/gamma-launcher#54]
Hi,
just like in the title - the script cannot execute because of this error.
The following is my entire output after using a command:

```
[+] Updating G.A.M.M.A. definition
    downloading archive...
Traceback (most recent call last):
  File "gamma-launcher", line 8, in <module>
  File "launcher/cli.py", line 64, in main
  File "launcher/commands/install.py", line 204, in run
  File "launcher/commands/install.py", line 68, in _update_gamma_definition
  File "launcher/downloader/base.py", line 34, in download
FileNotFoundError: [Errno 2] No such file or directory: "/media/GAMES-H/Games/ZDALGER/GAMMA/.Grok's Modpack Installer/GAMMA_definition.zip"
[1241253] Failed to execute script 'gamma-launcher' due to unhandled exception!
```

The following is the command I'm using:

`./gamma-launcher full-install --anomaly /media/GAMES-H/Games/ZDALGER/ANOMALY --gamma /media/GAMES-H/Games/ZDALGER/GAMMA`

Thank you for any help in advance

**Comment by Mord3rca** [comment]
Hello, apparently, launcher cannot fetch this file: https://github.com/Grokitach/Stalker_GAMMA/archive/refs/heads/main.zip

Can you provide **requests** version with `pip list | grep requests` ?
Unless you are using the standalone.

**Comment by alirgion** [comment]
> Hello, apparently, launcher cannot fetch this file: https://github.com/Grokitach/Stalker_GAMMA/archive/refs/heads/main.zip
> 
> Can you provide **requests** version with `pip list | grep requests` ? Unless you are using the standalone.


Here's the output:
`requests                 2.28.2
`

Thank you very much for your help

**Comment by Mord3rca** [comment]
Looks like to be a network issue.
Can you download the file with your web browser and put it in **/media/GAMES-H/Games/ZDALGER/GAMMA/.Grok's Modpack Installer/GAMMA_definition.zip** ?
It should be able to continue after that

**Comment by alirgion** [comment]
Unfortunately after doing so I get this output:

`./gamma-launcher full-install --anomaly /media/GAMES-H/Games/ZDALGER/ANOMALY --gamma /media/GAMES-H/Games/ZDALGER/GAMMA
[+] Updating G.A.M.M.A. definition
[+] Reading /media/GAMES-H/Games/ZDALGER/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & /media/GAMES-H/Games/ZDALGER/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
[+] Installing mod:  Dux Characters Kit Voices Pack
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
Traceback (most recent call last):
  File "tenacity/__init__.py", line 382, in __call__
  File "launcher/downloader/__init__.py", line 30, in download_mod
  File "launcher/downloader/base.py", line 34, in download
FileNotFoundError: [Errno 2] No such file or directory: '/media/GAMES-H/Games/ZDALGER/GAMMA/downloads/Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gamma-launcher", line 8, in <module>
  File "launcher/cli.py", line 64, in main
  File "launcher/commands/install.py", line 208, in run
  File "launcher/commands/install.py", line 170, in _install_mods
  File "launcher/commands/install.py", line 132, in _install_mod
  File "tenacity/__init__.py", line 289, in wrapped_f
  File "tenacity/__init__.py", line 379, in __call__
  File "tenacity/__init__.py", line 326, in iter
tenacity.RetryError: RetryError[<Future at 0x7f3e9a6bce10 state=finished raised FileNotFoundError>]
[23556] Failed to execute script 'gamma-launcher' due to unhandled exception!
`

**Comment by Mord3rca** [comment]
Do you have a firewall or something ?
Which distro are you using ?

Looks like `gamma-launcher` is failing all downloads.

**Comment by alirgion** [comment]
I'm using EndeavourOS with BSPWM. I do have firewalld installed but even with it stopped the same error appears.

**Comment by Mord3rca** [comment]
ufw ? opensnitch ? ...

**Comment by alirgion** [comment]
Both ufw and opensnitch are not present on my system

**Comment by Mord3rca** [comment]
Just tested in a VM on a fresh install of EndeavourOS.

No issue, everything is downloading fine. This problem is setup dependent

**Comment by alirgion** [comment]
I have tried reinstalling Endeavour without a firewall, trying a different Endeavour edition, running the script from the live environment as well as installing it from another distro (Pop_OS) just as a sanity check. I have gotten the same error every single time. What can I be doing wrong? Thank you for your help in advance, I really appreciate it.

**Comment by Mord3rca** [comment]
Can you resolve / ping github & moddb from your computer (the one with the launcher) ?
```sh
ping -4 -c 5 github.com
ping -4 -c 5 www.moddb.com
```

**Comment by alirgion** [comment]
Both addresses resolve and ping correctly. As an extra sanity check I tried this script on my Steam Deck and got the same error I have reported on my first post.

**Comment by Mord3rca** [comment]
Can you install everything in a venv ? So you can edit files to get the status code of the HTTP response & text of it ?

Apply this before installing / exec it:
```
diff --git a/launcher/downloader/base.py b/launcher/downloader/base.py
index 2efe2b3..0bafc87 100644
--- a/launcher/downloader/base.py
+++ b/launcher/downloader/base.py
@@ -33,6 +33,8 @@ class Base(ABC):
         h = md5()
         with open(path, 'wb') as f:
             r = g_session.get(self._url)
+            print(f"-- HTTP ANSWER: {r.status_code}--")
+            print(r.text)
             for chunk in r.iter_content(chunk_size=1 * 1024 * 1024):
                 if chunk:
                     f.write(chunk)
```

**Comment by alirgion** [comment]
I tried installing it in venv, but your command did not work - I got the following:
```
diff: unrecognized option '--git'
diff: Try 'diff --help' for more information.
```


After adding those two lines 
```
print(f"-- HTTP ANSWER: {r.status_code}--")
print(r.text)
```
 manually to the file my error after running an install looked like this

```
gamma-launcher full-install --anomaly /run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/ANOMALY/ --gamma /run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/GAMMA/
[+] Updating G.A.M.M.A. definition
[+] Reading /run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & /run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
[+] Installing mod:  Dux Characters Kit Voices Pack
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
  - Downloading Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
Traceback (most recent call last):
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/launcher/downloader/__init__.py", line 30, in download_mod
    e.download(file)
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/launcher/downloader/base.py", line 34, in download
    with open(path, 'wb') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/GAMMA/downloads/Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/launcher/commands/install.py", line 208, in run
    self._install_mods()
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/launcher/commands/install.py", line 170, in _install_mods
    self._install_mod(k, v)
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/launcher/commands/install.py", line 132, in _install_mod
    file = download_mod(url, self._dl_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/env/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f021dde1910 state=finished raised FileNotFoundError>]
```

**Comment by Mord3rca** [comment]
Is **/run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/GAMMA/downloads/** folder exist ?
if not: `mkdir -p /run/media/aryphy/8A00EC5500EC4A31/Games/ZDALGER/GAMMA/downloads/` and launcher should work now.

**Comment by Mord3rca** [comment]
Did you try to create the folder ? Did it fix the issue ?

**Comment by aryphy** [comment]
No, it unfortunately did not solve the issue for me.

```
gamma-launcher full-install --anomaly /media/aryphy/GAMES-G/Stalker/Anomaly/ --gamma /media/aryphy/GAMES-G/Stalker/GAMMA/
[+] Updating G.A.M.M.A. definition
    downloading archive...
Traceback (most recent call last):
  File "/media/aryphy/GAMES-G/Stalker/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 204, in run
    self._update_gamma_definition()
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 68, in _update_gamma_definition
    g.download(gdef)
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/downloader/base.py", line 34, in download
    with open(path, 'wb') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "/media/aryphy/GAMES-G/Stalker/GAMMA/.Grok's Modpack Installer/GAMMA_definition.zip"
(env) [aryphy@aryphy-pc Stalker]$ gamma-launcher full-install --anomaly /media/aryphy/GAMES-G/Stalker/Anomaly/ --gamma /media/aryphy/GAMES-G/Stalker/GAMMA/
[+] Updating G.A.M.M.A. definition
    downloading archive...
Traceback (most recent call last):
  File "/media/aryphy/GAMES-G/Stalker/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 204, in run
    self._update_gamma_definition()
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 68, in _update_gamma_definition
    g.download(gdef)
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/downloader/base.py", line 34, in download
    with open(path, 'wb') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "/media/aryphy/GAMES-G/Stalker/GAMMA/.Grok's Modpack Installer/GAMMA_definition.zip"
```

**Comment by Mord3rca** [comment]
Did you followed this setup https://github.com/DravenusRex/stalker-gamma-linux-guide ? Also, it looks like you are recreating a new folder each time. That won't make the debug task easier.

**Comment by aryphy** [comment]
Yes, I was following this exact guide, and since the first step is to download files with the launcher I can't go further.

Also, I do apologise for changing the folders, but I have reformatted the drive to ext4 instead of using ntfs-3g since I've thought this might be the issue.

**Comment by Mord3rca** [comment]
Something is definitely wrong with your setup since you don't have some critical folder available.

Can you do the following commands:
```sh
$ ls -la /media/aryphy/GAMES-G/Stalker/Anomaly
$ ls -la /media/aryphy/GAMES-G/Stalker/GAMMA
$ ls -la "/media/aryphy/GAMES-G/Stalker/GAMMA/.Grok's Modpack Installer"
```

**Comment by aryphy** [comment]
This is what I got after running those commands

```
[aryphy@aryphy-pc Stalker]$ ls -la /media/aryphy/GAMES-G/Stalker/Anomaly
total 8
drwxr-xr-x 2 aryphy aryphy 4096 09-20 17:41 .
drwxr-xr-x 6 aryphy aryphy 4096 09-20 17:43 ..
[aryphy@aryphy-pc Stalker]$ ls -la /media/aryphy/GAMES-G/Stalker/GAMMA
total 12
drwxr-xr-x 3 aryphy aryphy 4096 09-20 17:30  .
drwxr-xr-x 6 aryphy aryphy 4096 09-20 17:43  ..
drwxr-xr-x 2 aryphy aryphy 4096 09-20 17:30 ".Grok's Modpack Installer"
[aryphy@aryphy-pc Stalker]$ ls -la "/media/aryphy/GAMES-G/Stalker/GAMMA/.Grok's Modpack Installer"
total 8
drwxr-xr-x 2 aryphy aryphy 4096 09-20 17:30 .
drwxr-xr-x 3 aryphy aryphy 4096 09-20 17:30 ..

```

I'm also attaching full logs of my install below

```
[aryphy@aryphy-pc Stalker]$ python3 -m venv env
[aryphy@aryphy-pc Stalker]$ source env/bin/activate
(env) [aryphy@aryphy-pc Stalker]$ which python
/media/aryphy/GAMES-G/Stalker/env/bin/python
(env) [aryphy@aryphy-pc Stalker]$ pip install --upgrade pip
Requirement already satisfied: pip in ./env/lib/python3.11/site-packages (23.2.1)
(env) [aryphy@aryphy-pc Stalker]$ pip install .
Processing /media/aryphy/GAMES-G/Stalker
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bs4 (from gamma-launcher==1.3)
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting py7zr (from gamma-launcher==1.3)
  Obtaining dependency information for py7zr from https://files.pythonhosted.org/packages/2c/da/155bb1f692c067b9213c9c7b8c19a012a65027399606d623a25dfb1d3af1/py7zr-0.20.6-py3-none-any.whl.metadata
  Using cached py7zr-0.20.6-py3-none-any.whl.metadata (16 kB)
Collecting rarfile (from gamma-launcher==1.3)
  Obtaining dependency information for rarfile from https://files.pythonhosted.org/packages/75/34/f06b7de74bcea328d8d7a950aad099c1100578cc3960ffc5a00d30ab511c/rarfile-4.1-py3-none-any.whl.metadata
  Using cached rarfile-4.1-py3-none-any.whl.metadata (4.4 kB)
Collecting requests (from gamma-launcher==1.3)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting tenacity (from gamma-launcher==1.3)
  Obtaining dependency information for tenacity from https://files.pythonhosted.org/packages/f4/f1/990741d5bb2487d529d20a433210ffa136a367751e454214013b441c4575/tenacity-8.2.3-py3-none-any.whl.metadata
  Using cached tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Collecting beautifulsoup4 (from bs4->gamma-launcher==1.3)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting texttable (from py7zr->gamma-launcher==1.3)
  Using cached texttable-1.6.7-py2.py3-none-any.whl (10 kB)
Collecting pycryptodomex>=3.6.6 (from py7zr->gamma-launcher==1.3)
  Obtaining dependency information for pycryptodomex>=3.6.6 from https://files.pythonhosted.org/packages/23/23/3f3d042c96ff7bece5b126365593b1f9c8e3ae62ce80d44e9da39c5e8a73/pycryptodomex-3.19.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached pycryptodomex-3.19.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pyzstd>=0.14.4 (from py7zr->gamma-launcher==1.3)
  Obtaining dependency information for pyzstd>=0.14.4 from https://files.pythonhosted.org/packages/c3/7f/0d5c048cacb906fa40485b5bb9dc5de5993bff2e4c85fa77e5a89c413205/pyzstd-0.15.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached pyzstd-0.15.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Collecting pyppmd<1.1.0,>=0.18.1 (from py7zr->gamma-launcher==1.3)
  Using cached pyppmd-1.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Collecting pybcj>=0.6.0 (from py7zr->gamma-launcher==1.3)
  Using cached pybcj-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (50 kB)
Collecting multivolumefile>=0.2.3 (from py7zr->gamma-launcher==1.3)
  Using cached multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Collecting brotli>=1.0.9 (from py7zr->gamma-launcher==1.3)
  Obtaining dependency information for brotli>=1.0.9 from https://files.pythonhosted.org/packages/b3/e7/ca2993c7682d8629b62630ebf0d1f3bb3d579e667ce8e7ca03a0a0576a2d/Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting inflate64>=0.3.1 (from py7zr->gamma-launcher==1.3)
  Using cached inflate64-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (95 kB)
Collecting psutil (from py7zr->gamma-launcher==1.3)
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting charset-normalizer<4,>=2 (from requests->gamma-launcher==1.3)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/bc/85/ef25d4ba14c7653c3020a1c6e1a7413e6791ef36a0ac177efa605fc2c737/charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Collecting idna<4,>=2.5 (from requests->gamma-launcher==1.3)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->gamma-launcher==1.3)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/37/dc/399e63f5d1d96bb643404ee830657f4dfcf8503f5ba8fa3c6d465d0c57fe/urllib3-2.0.5-py3-none-any.whl.metadata
  Using cached urllib3-2.0.5-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests->gamma-launcher==1.3)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4->gamma-launcher==1.3)
  Obtaining dependency information for soupsieve>1.2 from https://files.pythonhosted.org/packages/4c/f3/038b302fdfbe3be7da016777069f26ceefe11a681055ea1f7817546508e3/soupsieve-2.5-py3-none-any.whl.metadata
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Using cached py7zr-0.20.6-py3-none-any.whl (66 kB)
Using cached rarfile-4.1-py3-none-any.whl (28 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Using cached Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
Using cached pycryptodomex-3.19.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached pyzstd-0.15.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (412 kB)
Using cached urllib3-2.0.5-py3-none-any.whl (123 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Building wheels for collected packages: gamma-launcher
  Building wheel for gamma-launcher (pyproject.toml) ... done
  Created wheel for gamma-launcher: filename=gamma_launcher-1.3-py3-none-any.whl size=27966 sha256=a62f2a477623b1035a23038577ab4fed623bbf58aa72ee4d6e33d17412e8d1ad
  Stored in directory: /tmp/pip-ephem-wheel-cache-0q273p12/wheels/6d/53/2c/c252ce33c3a5eafcc5a77b58a5aa7ce453c30a79849cbcf381
Successfully built gamma-launcher
Installing collected packages: texttable, brotli, urllib3, tenacity, soupsieve, rarfile, pyzstd, pyppmd, pycryptodomex, pybcj, psutil, multivolumefile, inflate64, idna, charset-normalizer, certifi, requests, py7zr, beautifulsoup4, bs4, gamma-launcher
Successfully installed beautifulsoup4-4.12.2 brotli-1.1.0 bs4-0.0.1 certifi-2023.7.22 charset-normalizer-3.2.0 gamma-launcher-1.3 idna-3.4 inflate64-0.3.1 multivolumefile-0.2.3 psutil-5.9.5 py7zr-0.20.6 pybcj-1.0.1 pycryptodomex-3.19.0 pyppmd-1.0.0 pyzstd-0.15.9 rarfile-4.1 requests-2.31.0 soupsieve-2.5 tenacity-8.2.3 texttable-1.6.7 urllib3-2.0.5
(env) [aryphy@aryphy-pc Stalker]$ gamma-launcher full-install --anomaly /media/aryphy/GAMES-G/Games/Stalker/ANOMALY --gamma /media/aryphy/GAMES-G/Games/Stalker/GAMMA
[+] Updating G.A.M.M.A. definition
    downloading archive...
Traceback (most recent call last):
  File "/media/aryphy/GAMES-G/Stalker/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/cli.py", line 64, in main
    args.cobject().run(args)
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 204, in run
    self._update_gamma_definition()
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/commands/install.py", line 68, in _update_gamma_definition
    g.download(gdef)
  File "/media/aryphy/GAMES-G/Stalker/env/lib/python3.11/site-packages/launcher/downloader/base.py", line 34, in download
    with open(path, 'wb') as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "/media/aryphy/GAMES-G/Games/Stalker/GAMMA/.Grok's Modpack Installer/GAMMA_definition.zip"
(env) [aryphy@aryphy-pc Stalker]$ 

```

**Comment by Mord3rca** [comment]
You need to install Anomaly 1.5.2 in Anomaly dir & extract Gamma RC3 in gamma directory as instructed [here](https://github.com/DravenusRex/stalker-gamma-linux-guide).

For GAMMA RC3, you can find it on discord or use a mirror.

**Comment by aryphy** [comment]
Thank you for your help. I'm sorry to have wasted so much time on me just being an idiot. It worked perfectly.

Now I just have to deal with an issue with GAMMA itself not launching, due to "Unhandled exception", though I have no idea what's causing it.

Thank you again, and once again - sorry.
