### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by DravenusRex** [Mord3rca/gamma-launcher#7]
Sometimes when downloading a mod this will happen:
```
Traceback (most recent call last):
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dravenusrex/games/gamma-launcher-venv/bin/gamma-launcher", line 33, in <module>
    sys.exit(load_entry_point('launcher==0.1', 'console_scripts', 'gamma-launcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/launcher/cli.py", line 60, in main
    args.cobject().run(args)
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/launcher/commands/install.py", line 164, in run
    self._install_mods()
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/launcher/commands/install.py", line 130, in _install_mods
    self._install_mod(k, v)
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/launcher/commands/install.py", line 91, in _install_mod
    e.download(filename)
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/launcher/downloader/base.py", line 35, in download
    r = g_session.get(self._url)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dravenusrex/games/gamma-launcher-venv/lib/python3.11/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
I'm under the impression that this is a natural issue with the servers the mods are hosted on.
It seems like the only way to handle this at the moment is to delete the incomplete file it was downloading and restart the installation.
Eventually you will get all the files completed after a few of them go through connection errors.
Perhaps whenever this happens it could be handled by automatically deleting the file and queuing the download for later.

**Comment by Mord3rca** [comment]
This is dependent of ModDB mirrors & your connection. To avoid to redo all the installation, I've made a PR to retry downloading 3 times.

Hopefully, it will mitigate this issue.
