### ISSUE TITLE
No attribute '_check_tmp_free_space'

### ISSUE THREAD

**Issue by RedJ1ve** [Mord3rca/gamma-launcher#75]
Hi, I'm getting the error when doing a full install.

```
Traceback (most recent call last):
  File "/home/aecyr/Games/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aecyr/Games/gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 70, in main
    args.cobject().run(args)
  File "/home/aecyr/Games/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 406, in run
    GammaSetup().run(args)
  File "/home/aecyr/Games/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 157, in run
    self._check_tmp_free_space(5)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GammaSetup' object has no attribute '_check_tmp_free_space'
(env) 
```

I have more than enough space left at 192G, and I have confirmed that I have my TMPDIR env variable set. Anomaly install also worked perfectly. I am running Nixos, which does tend to cause issues, but this seems unrelated?

**Comment by Mord3rca** [comment]
Woops, this should fix the issue: https://github.com/Mord3rca/gamma-launcher/commit/be8c68f34fa4a93f95622f8163d4f0482899ea5f

This commit is on branch `improving_code`, reinstall launcher on this branch and everything should be fine... Or use a cache directory to bypass the issue

**Comment by xo-xo-xo-xo** [comment]
Unsure if this is related, but I've also downloaded the newest branch, verified my tmpdir had been exported to somewhere with adequate space (~/tmp) and I'm getting this error instead:

```(env) xo@xo:gamma-launcher-improving_code☸ gamma-launcher full-install --anomaly ~/Games/Anomaly/ --gamma ~/Games/GAMMA/
[+] Updating G.A.M.M.A. definition
[+] Reading /home/xo/Games/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modlist.txt & /home/xo/Games/GAMMA/.Grok's Modpack Installer/G.A.M.M.A/modpack_data/modpack_maker_list.txt...
[+] Installing mod:  Dux Characters Kit Voices Pack
  - Using cached Duxs_Innumerable_Character_Kit_Voices_Pack.2.zip
    Installing Dux's Innumerable Character Kit Voices Pack -> /home/xo/Games/GAMMA/mods/305- Dux Characters Kit Voices Pack - Demonized
    Installing Dux's Innumerable Character Kit Voices Pack English ISG -> /home/xo/Games/GAMMA/mods/305- Dux Characters Kit Voices Pack - Demonized
[+] Installing mod:  Grulag's Dead Bushes
  - Using cached gamma_large_files_v2.zip
    Installing Grulag's Dead Bushes -> /home/xo/Games/GAMMA/mods/272- Grulag's Dead Bushes - Grulag
[+] Installing mod:  Headlamp Animation Fix
  - Using cached HeadlampAnimationFix.3.zip
    Installing HeadlampAnimationFix -> /home/xo/Games/GAMMA/mods/270- Headlamp Animation Fix - RavenAscendant
[+] Installing mod:  Safe Areas Transitions
  - Using cached Safe_Start_2.2.zip
[+] Installing mod:  Zone Customization Project (ZCP)
  - Using cached zone_customization_project_1.5e.zip
[+] Installing mod:  Weird Tasks Framework
  - Using cached WTF_3.6.zip
    Installing Weird_Tasks_Framework -> /home/xo/Games/GAMMA/mods/244- Weird Tasks Framework - Igigog
[+] Installing mod:  Bizon Replacer
  - Using cached Better_Bizon_Weapon.7.7z
[+] Installing mod:  Xenotech Protects Cordon Base
  - Using cached Combat_Behavior_1.02.4.rar
    Installing Xenotech, Seryoga, Gonta, Crab, Garmata, Pilot, Tourist combat behavior  -> /home/xo/Games/GAMMA/mods/232- Xenotech Protects Cordon Base - Malac88
    WARNING: Xenotech, Seryoga, Gonta, Crab, Garmata, Pilot, Tourist combat behavior  does not exist
[+] Installing mod:  More Aggressive NPC Looting (harder game, do not use with NPC Loot Claim)
  - Using cached More_Aggressive_NPC_Looting.1.zip
    Installing More Aggressive NPC Looting -> /home/xo/Games/GAMMA/mods/231- More Aggressive NPC Looting (harder game, do not use with NPC Loot Claim) - Demonized
[+] Installing mod:  Monsters Unstucker
  - Using cached Monster_Unstucker.3.zip
    Installing Monster Unstucker -> /home/xo/Games/GAMMA/mods/229- Monsters Unstucker - Demonized
[+] Installing mod:  Russian Localization
  - Using cached Russian_Localization_RC3.1.7z
    Installing Russian Localization RC3 -> /home/xo/Games/GAMMA/mods/228- Russian Localization - oneonline911
[+] Installing mod:  Trader Overhaul (if you do not want the true GAMMA experience)
  - Using cached 1.5.2_Update_Version.zip
    Installing Trader Overhaul (Main Folder) -> /home/xo/Games/GAMMA/mods/213- Trader Overhaul (if you do not want the true GAMMA experience) - AGoodSetOfPistol
[+] Installing mod:  NPC Loot Claim (NPCs will kill you if you loot what they killed)
  - Using cached No-sortingNPC_Loot_Claim-Continued.-v1.0.6.2-Bugfix.rar
[+] Installing mod:  Death Animations (if you like shooting extra ammo on dead people)
  - Using cached Stealth_2.3.zip
    Installing (Patch) Death Animations -> /home/xo/Games/GAMMA/mods/209- Death Animations (if you like shooting extra ammo on dead people) - xcvb
[+] Installing mod:  Anomaly Magazines (Disable G.A.M.M.A. Unjam Reload)
  - Using cached MagsRedux.zip
    Installing MagsRedux-main -> /home/xo/Games/GAMMA/mods/207- Anomaly Magazines (Disable G.A.M.M.A. Unjam Reload) - RavenAscendant
    Installing aug_patch -> /home/xo/Games/GAMMA/mods/207- Anomaly Magazines (Disable G.A.M.M.A. Unjam Reload) - RavenAscendant
    Installing bas_patch -> /home/xo/Games/GAMMA/mods/207- Anomaly Magazines (Disable G.A.M.M.A. Unjam Reload) - RavenAscendant
    Installing ppp_patch -> /home/xo/Games/GAMMA/mods/207- Anomaly Magazines (Disable G.A.M.M.A. Unjam Reload) - RavenAscendant
[+] Installing mod:  Limited Fast Travel (walking is good for your health)
  - Using cached Limited_Fast_Travel.1.zip
    Installing Limited Fast Travel -> /home/xo/Games/GAMMA/mods/204- Limited Fast Travel (walking is good for your health) - Demonized
[+] Installing mod:  Hunger Thirst Sleep UI htsb knifebinoc patches
  - Using cached HTS_bars_1.01.zip
    Installing 00. UI Main -> /home/xo/Games/GAMMA/mods/165- Hunger Thirst Sleep UI htsb knifebinoc patches - xcvb
[+] Installing mod:  Hunger Thirst Sleep UI
  - Using cached HTS_bars_1.01.zip
    Installing 00. UI Main -> /home/xo/Games/GAMMA/mods/164- Hunger Thirst Sleep UI - xcvb
[+] Installing mod:  Cordon Early Game Tweak
  - Using cached firstday_cordon.rar
[+] Installing mod:  No more companions friendly fire
  - Using cached nomorecompanionfriendlyfireu.zip
[+] Installing mod:  Mutants Bleeding
  - Using cached ArszisMutantBleeding2_0_1.zip
[+] Installing mod:  Lsz AI tweak
  - Using cached Lsz.9.rar
Traceback (most recent call last):
  File "/home/xo/gamma-launcher-improving_code/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/launcher/cli.py", line 68, in main
    args.cobject().run(args)
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/launcher/commands/install.py", line 415, in run
    self._install_mods()
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/launcher/commands/install.py", line 366, in _install_mods
    self._install_mod(k, v)
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/launcher/commands/install.py", line 332, in _install_mod
    extract_archive(file, dir)
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/launcher/archive.py", line 57, in extract_archive
    _extract_func_dict.get(ext)(filename, path)
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/launcher/archive.py", line 49, in <lambda>
    'rar': lambda f, p: RarFile(f).extractall(p),
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/rarfile.py", line 875, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/rarfile.py", line 940, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/rarfile.py", line 955, in _make_file
    shutil.copyfileobj(src, dst)
  File "/usr/lib64/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/xo/gamma-launcher-improving_code/env/lib64/python3.11/site-packages/rarfile.py", line 2284, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=65536 got=0
````

It seems to always happen on the ```Lsz AI tweak``` package.

**Comment by Mord3rca** [comment]
@xo-xo-xo-xo Lsz AI tweak is probably  corrupt, please run `gamma-launcher check-md5 --gamma <GAMMA Path> --update-cache` or delete corrupted archive and re-run full-install command.
