### ISSUE TITLE
TypeError when beginning Anomaly install

### ISSUE THREAD

**Issue by jupjohn** [Mord3rca/gamma-launcher#85]
When beginning an Anomaly install for the first time, the launcher throws a `TypeError` just after starting the install process. This prevents Anomaly from being installed.

Trace:
```
[+] Installing base Anomaly 1.5.1
Traceback (most recent call last):
  File "/home/[...]/gamma-launcher/env/bin/gamma-launcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/[...]/gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 68, in main
    args.cobject().run(args)
  File "/home/[...]/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 98, in run
    self._install_component("base-1.5.1", mime="application/x-7z-compressed+bcj2")
TypeError: AnomalyInstall._install_component() got an unexpected keyword argument 'mime'
```

Commit:  8de782b

**Comment by jupjohn** [comment]
This appears to be due to a missed parameter name change in f530b39. I'll create a PR to resolve this.
