### ISSUE TITLE
7z crc error

### ISSUE THREAD

**Issue by axet** [Mord3rca/gamma-launcher#87]
7z mod failed to install, even when archive is 100% correct:

```
7z t GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs 12th Gen Intel(R) Core(TM) i3-12100F (90675),ASM,AES-NI)

Scanning the drive for archives:
1 file, 879932061 bytes (840 MiB)

Testing archive: GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z
--
Path = GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z
Type = 7z
Physical Size = 879932061
Headers Size = 7557
Method = LZMA2:25
Solid = +
Blocks = 1

Everything is Ok                                                               

Folders: 206
Files: 474
Size:       4211157851
Compressed: 879932061
```

```
[+] Installing mod: Grass Tweaks (reinstall for different options)
  - Using cached Aydins_Grass_Tweaks_4.0.7z
Traceback (most recent call last):
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/bin/gamma-launcher", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/launcher/cli.py", line 68, in main
    args.cobject().run(args)
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 320, in run
    self._install_mods()
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/launcher/commands/install.py", line 271, in _install_mods
    mod.install(self._dl_dir, self._mod_dir)
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/launcher/mods/base.py", line 138, in install
    extract_archive(archive, dir)
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/launcher/archive.py", line 57, in extract_archive
    _extract_func_dict.get(mime)(filename, path)
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/launcher/archive.py", line 48, in <lambda>
    'application/x-7z-compressed': lambda f, p: SevenZipFile(f).extractall(p),
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 980, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 621, in _extract
    self.worker.extract(
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1225, in extract
    self.extract_single(
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1313, in extract_single
    raise e
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1310, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "/media/axet/1TB/Games/S.T.A.L.K.E.R. GAMMA/gamma-launcher/env/lib/python3.11/site-packages/py7zr/py7zr.py", line 1382, in _extract_single
    raise CrcError(crc32, f.crc32, f.filename)
py7zr.exceptions.CrcError: (3849332554, 2151791401, "Aydin's Grass Tweaks - SPRING TREES 4.0/gamedata/textures/lfo/lfo_trees/birch/trees_atp_birch_red_forest_c.dds")
```

**Comment by Mord3rca** [comment]
Hi,

Can you provide the following data:

`md5sum GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z` ?
For reference mine is **46c1245d066d9926c0885ce48f4db0ad**

`pip list` ?

**Comment by axet** [comment]
Yep

```
 md5sum GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z 
46c1245d066d9926c0885ce48f4db0ad  GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z
```


```
pip list
Package            Version
------------------ ----------
beautifulsoup4     4.12.2
Brotli             1.1.0
bs4                0.0.1
certifi            2023.11.17
charset-normalizer 3.3.2
gamma-launcher     1.5
idna               3.6
inflate64          1.0.0
multivolumefile    0.2.3
pip                23.3.2
psutil             5.9.7
py7zr              0.20.8
pybcj              1.0.2
pycryptodomex      3.19.1
pyppmd             1.1.0
python-magic       0.4.27
pyzstd             0.15.9
rarfile            4.1
requests           2.31.0
setuptools         66.1.1
soupsieve          2.5
tenacity           8.2.3
texttable          1.7.0
tqdm               4.66.1
urllib3            2.1.0
```

**Comment by axet** [comment]
It could be low memory issues. When I mount this HDD remotely using sshfs, I can install Aydins_Grass_Tweaks. No problem. Remote machine has 16GB. Machine above has only 4GB and 16GB SWAP... But I still has no confirmation.

**Comment by Mord3rca** [comment]
Can't reproduce on my side even after py7zr upgrade to v0.20.8.

Maybe the issue is caused by python version ? I'm using 3.11.7

**Comment by axet** [comment]
python 3.11.2

**Comment by axet** [comment]
I had to use this patch, and error is gone:

```diff
diff --git a/launcher/archive.py b/launcher/archive.py
index e84dc26..78a6ddd 100644
--- a/launcher/archive.py
+++ b/launcher/archive.py
@@ -45,7 +45,7 @@ else:
             raise RuntimeError(f'7z error will decompressing {f}')
 
     _extract_func_dict = {
-        'application/x-7z-compressed': lambda f, p: SevenZipFile(f).extractall(p),
+        'application/x-7z-compressed': _7zip_bcj2_workaround,
         'application/x-rar': lambda f, p: RarFile(f).extractall(p),
         'application/zip': lambda f, p: ZipFile(f).extractall(p),
         'application/x-7z-compressed+bcj2': _7zip_bcj2_workaround
```

**Comment by axet** [comment]
I guess I know what is going on. To reproduce the issue you need:

1) 4GB ram
2) 16GB swap
3) /tmp mounted as 'tmpfs size=12G'

py7z will extract archive into /tmp, tmpfs will relocate some of data into swapfile and reading data back from swap file will causing CRC errors.

This could be kernel issue. Only happens with Aydins_Grass_Tweaks. Other archives (smaller in size?) works fine.

**Comment by Mord3rca** [comment]
All extraction take place in **/tmp** if TMPDIR is not set

What was your current directory for this test ?

**Comment by axet** [comment]
GAMMA/..

**Comment by Mord3rca** [comment]
If the issue is caused by an error in TMPFS because of the swapping ... It is

Please extract in a `tempdir.TemporaryDirectory`

**Comment by axet** [comment]
If I set TMPDIR to HDD it works.

**Comment by axet** [comment]
```python
import py7zr
import tempfile

f="GAMMA/downloads/Aydins_Grass_Tweaks_4.0.7z"
with tempfile.TemporaryDirectory() as p:
  py7zr.SevenZipFile(f).extractall(p)
```

works as well. still somehow gamma-launcher related.

**Comment by Mord3rca** [comment]
> I guess I know what is going on. To reproduce the issue you need:
> 
>     1. 4GB ram
> 
>     2. 16GB swap
> 
>     3. /tmp mounted as 'tmpfs size=12G'
> 

In my opinion, issue is here. You system have 12GiB of tmpfs on a system running with 4GiB of RAM. Swapping / OOM can be triggered following configuration of your system.

+ Setting a different TMPDIR (to HDD) fix the issue.
